- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx server
      ansible.bultin.service:
        name: nginx
        state: present
        enabled: true